import type { ElementType } from "react";
import { type NavKey } from "@/lib/store";
import {
  LayoutDashboard,
  Users,
  Wallet,
  ArrowLeftRight,
  Landmark,
  CreditCard,
  BarChart3,
  ScrollText,
  Settings,
  ArrowLeft,
  Send,
  QrCode,
  MessageSquare,
  UsersRound,
  Repeat,
  Layers,
  Share2,
  TrendingUp,
  UserPlus,
  FileBarChart,
  Headphones,
  Coins,
  Briefcase,
  BookOpen,
  SlidersHorizontal,
  Folder,
  FileText,
  Truck,
  ShieldCheck,
  Inbox,
  History,
  Wrench,
} from "lucide-react";

export type NavItem = { key: NavKey; label: string; icon: ElementType; roles?: string[] };

export const NAV: NavItem[] = [
  { key: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { key: "service-center", label: "Service Center", icon: Headphones },
  { key: "customers", label: "Customers", icon: Users },
  { key: "accounts", label: "Accounts", icon: Wallet },
  { key: "transactions", label: "Transactions", icon: ArrowLeftRight },
  { key: "loans", label: "Loans", icon: Landmark },
  { key: "cards", label: "Cards", icon: CreditCard },
  { key: "gold-loans", label: "Gold Loans", icon: Coins },
  { key: "deposit-products", label: "Deposit Products", icon: Layers },
  { key: "shares", label: "Share Capital", icon: Share2 },
  { key: "overdrafts", label: "Overdrafts", icon: TrendingUp },
  { key: "payments", label: "NEFT/RTGS/IMPS", icon: Send },
  { key: "qr", label: "QR Banking", icon: QrCode },
  { key: "agents", label: "Field Agents", icon: UsersRound },
  { key: "standing-instructions", label: "Standing Instructions", icon: Repeat },
  { key: "member-enrollment", label: "Member Enrollment", icon: UserPlus },
  { key: "sms", label: "SMS Banking", icon: MessageSquare },
  { key: "hr", label: "HR Module", icon: Briefcase },
  { key: "groups", label: "Account Groups", icon: Folder },
  { key: "ledgers", label: "Ledgers", icon: BookOpen },
  { key: "vouchers", label: "Vouchers", icon: FileText },
  { key: "vendors", label: "Vendors", icon: Truck },
  { key: "accounting", label: "Accounting", icon: BookOpen },
  { key: "menu-rights", label: "Menu Rights", icon: ShieldCheck, roles: ["ADMIN"] },
  { key: "requests", label: "Requests", icon: Inbox },
  { key: "modification", label: "Modification Log", icon: History },
  { key: "bank-reconciliation", label: "Bank Reconciliation", icon: ArrowLeft },
  { key: "specialized-reports", label: "Specialized Reports", icon: FileBarChart },
  { key: "tools", label: "Tools", icon: Wrench, roles: ["ADMIN"] },
  { key: "master-settings", label: "Master Settings", icon: SlidersHorizontal, roles: ["ADMIN"] },
  { key: "reports", label: "Reports", icon: BarChart3 },
  { key: "audit", label: "Audit Log", icon: ScrollText },
  { key: "settings", label: "Settings", icon: Settings, roles: ["ADMIN", "MANAGER"] },
];

export const TITLE: Record<NavKey, string> = {
  dashboard: "Dashboard Overview",
  "service-center": "Service Center",
  customers: "Customer Management",
  accounts: "Account Operations",
  transactions: "Transactions",
  loans: "Loan Management",
  cards: "Card Management",
  "gold-loans": "Gold Loan Management",
  "deposit-products": "Deposit Products",
  shares: "Share Capital",
  overdrafts: "Overdraft Facility",
  payments: "NEFT / RTGS / IMPS Payments",
  qr: "QR Banking",
  sms: "SMS Banking",
  agents: "Field Agents & Collections",
  "standing-instructions": "Standing Instructions",
  "member-enrollment": "Member Enrollment",
  hr: "HR Module",
  accounting: "Accounting",
  groups: "Account Groups",
  ledgers: "Ledgers",
  vouchers: "Vouchers",
  vendors: "Manage Vendors",
  "menu-rights": "Designation Menu Rights",
  requests: "Approval Requests",
  modification: "Modification Log",
  tools: "System Tools",
  "bank-reconciliation": "Bank Reconciliation & E-Collection",
  "specialized-reports": "Specialized Reports",
  "master-settings": "Master Settings",
  reports: "Reports & Analytics",
  audit: "Audit Trail",
  settings: "System Settings",
};

/** Nav entries the given role is allowed to see. */
export function navItemsFor(role: string): NavItem[] {
  return NAV.filter((n) => !n.roles || n.roles.includes(role));
}
